### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by philsmithsonuk** [aaronksaunders/ios8documemtpicker#1]
_Obligatory thank you message: thanks for starting this module development, it's very much appreciated. Been looking for some news from Appcelerator on this for a couple of weeks now but couldn't find anything_

I've never had to build a native iOS module before but I've done these steps so far:
1. Updated TITANIUM_SDK path in ./iphone/titanium.xconfig
2. Updated license and copyright in ./iphone/manifest to non-default values
3. Double checked location of TITANIUM_SDK path is correct
4. Run ./iphone/build.py
   The build seems to go fine and I see BUILD SUCCEEDED.

In the ./iphone/build folder I see "Release-iphoneos" and "Release-iphonesimulator" folders.  Inside both folders is a file called "libComCiIos8documemtpicker.a".  Same thing happens if I build from XCode. 

Upon building, I was expecting to see a generated ZIP file in the build folder which I would then install into the project.  

Any ideas what I'm doing wrong?

**Comment by aaronksaunders** [comment]
The easier approach is to open the project in titanium studio and select publish... the menu will provide the remainder of the instructions

**Comment by philsmithsonuk** [comment]
thanks, when I selected to build + install to a project from Titanium Studio, it works as expected
